-- Add missing columns to user_stats table
ALTER TABLE user_stats 
ADD COLUMN IF NOT EXISTS total_xp INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS max_stamina INTEGER NOT NULL DEFAULT 100;